import type { Backlink, BacklinkOverview, CompetitorBacklink, LinkProfile } from "@/features/backlinks/types";
import { DEMO_SITE_ID } from "@/features/demo/demoData";

const now = Date.now();
const DAY = 86_400_000;
const iso = (msAgo: number) => new Date(now - msAgo).toISOString();

export const demoBacklinks: Backlink[] = [
  {
    _id: "demo-bl-1",
    siteId: DEMO_SITE_ID,
    sourceUrl: "https://devweekly.example/newsletter/142",
    sourceDomain: "devweekly.example",
    targetUrl: "https://acme.example/",
    anchorText: "Acme",
    rel: "follow",
    isImage: false,
    origin: "referral",
    status: "live",
    httpStatus: 200,
    authority: 61,
    referralVisits: 284,
    lastReferralAt: iso(1 * DAY),
    lastLiveAt: iso(1 * DAY),
    lostAt: null,
    lastCheckedAt: iso(1 * DAY),
    lastError: "",
    createdAt: iso(40 * DAY),
  },
  {
    _id: "demo-bl-2",
    siteId: DEMO_SITE_ID,
    sourceUrl: "https://toolstack.example/best-deploy-tools",
    sourceDomain: "toolstack.example",
    targetUrl: "https://acme.example/pricing",
    anchorText: "Acme's pricing page",
    rel: "follow",
    isImage: false,
    origin: "index",
    status: "live",
    httpStatus: 200,
    authority: 72,
    referralVisits: 156,
    lastReferralAt: iso(3 * DAY),
    lastLiveAt: iso(3 * DAY),
    lostAt: null,
    lastCheckedAt: iso(3 * DAY),
    lastError: "",
    createdAt: iso(55 * DAY),
  },
  {
    _id: "demo-bl-3",
    siteId: DEMO_SITE_ID,
    sourceUrl: "https://news.ycombinator.com/item?id=39912345",
    sourceDomain: "news.ycombinator.com",
    targetUrl: "https://acme.example/blog/launch",
    anchorText: "acme.example",
    rel: "nofollow",
    isImage: false,
    origin: "referral",
    status: "live",
    httpStatus: 200,
    authority: 93,
    referralVisits: 1_840,
    lastReferralAt: iso(6 * DAY),
    lastLiveAt: iso(6 * DAY),
    lostAt: null,
    lastCheckedAt: iso(6 * DAY),
    lastError: "",
    createdAt: iso(6 * DAY),
  },
  {
    _id: "demo-bl-4",
    siteId: DEMO_SITE_ID,
    sourceUrl: "https://communityforum.example/t/acme-review/88",
    sourceDomain: "communityforum.example",
    targetUrl: "https://acme.example/",
    anchorText: "acme.example",
    rel: "ugc",
    isImage: false,
    origin: "scan",
    status: "live",
    httpStatus: 200,
    authority: 34,
    referralVisits: 42,
    lastReferralAt: iso(12 * DAY),
    lastLiveAt: iso(12 * DAY),
    lostAt: null,
    lastCheckedAt: iso(2 * DAY),
    lastError: "",
    createdAt: iso(30 * DAY),
  },
  {
    _id: "demo-bl-5",
    siteId: DEMO_SITE_ID,
    sourceUrl: "https://directoryoftools.example/listings/acme",
    sourceDomain: "directoryoftools.example",
    targetUrl: "https://acme.example/",
    anchorText: "Acme — developer tools",
    rel: "sponsored",
    isImage: false,
    origin: "manual",
    status: "live",
    httpStatus: 200,
    authority: 48,
    referralVisits: 19,
    lastReferralAt: iso(18 * DAY),
    lastLiveAt: iso(18 * DAY),
    lostAt: null,
    lastCheckedAt: iso(4 * DAY),
    lastError: "",
    createdAt: iso(18 * DAY),
  },
  {
    _id: "demo-bl-6",
    siteId: DEMO_SITE_ID,
    sourceUrl: "https://oldblog.example/2025/acme-writeup",
    sourceDomain: "oldblog.example",
    targetUrl: "https://acme.example/features",
    anchorText: "developer tools that get out of the way",
    rel: "follow",
    isImage: false,
    origin: "index",
    status: "lost",
    httpStatus: 404,
    authority: 29,
    referralVisits: 0,
    lastReferralAt: null,
    lastLiveAt: iso(45 * DAY),
    lostAt: iso(10 * DAY),
    lastCheckedAt: iso(10 * DAY),
    lastError: "Page returned 404",
    createdAt: iso(70 * DAY),
  },
  {
    _id: "demo-bl-7",
    siteId: DEMO_SITE_ID,
    sourceUrl: "https://partner.example/integrations/acme",
    sourceDomain: "partner.example",
    targetUrl: "https://acme.example/docs",
    anchorText: "",
    rel: "follow",
    isImage: true,
    origin: "manual",
    status: "pending",
    httpStatus: null,
    authority: null,
    referralVisits: 0,
    lastReferralAt: null,
    lastLiveAt: null,
    lostAt: null,
    lastCheckedAt: null,
    lastError: "",
    createdAt: iso(2 * 60 * 60_000),
  },
];

const mineProfile: LinkProfile = {
  totalLinks: 6,
  referringDomains: 6,
  followShare: 50,
  avgAuthority: 56,
  rel: { follow: 3, nofollow: 1, ugc: 1, sponsored: 1 },
  anchors: { branded: 2, keyword: 1, url: 2, generic: 0, image: 1 },
  sources: { editorial: 2, directory: 1, community: 2, social: 1 },
  topAnchors: [
    { text: "Acme", count: 1, kind: "branded" },
    { text: "acme.example", count: 2, kind: "url" },
    { text: "Acme's pricing page", count: 1, kind: "keyword" },
  ],
  topDomains: [
    { domain: "news.ycombinator.com", links: 1, authority: 93, kind: "social" },
    { domain: "toolstack.example", links: 1, authority: 72, kind: "editorial" },
    { domain: "devweekly.example", links: 1, authority: 61, kind: "editorial" },
  ],
  insights: [
    {
      id: "demo-insight-1",
      tone: "strength",
      title: "A high-authority mention is driving real traffic",
      detail: "The Hacker News thread alone has sent 1,840 visits in the last week — nofollow, but valuable for discovery.",
    },
    {
      id: "demo-insight-2",
      tone: "risk",
      title: "One link was lost this month",
      detail: "oldblog.example stopped linking to /features after a 404. Reach out or let it drop.",
    },
  ],
};

const rivalProfile: LinkProfile = {
  totalLinks: 4,
  referringDomains: 4,
  followShare: 75,
  avgAuthority: 64,
  rel: { follow: 3, nofollow: 1, ugc: 0, sponsored: 0 },
  anchors: { branded: 2, keyword: 1, url: 1, generic: 0, image: 0 },
  sources: { editorial: 3, directory: 1, community: 0, social: 0 },
  topAnchors: [
    { text: "Rival", count: 2, kind: "branded" },
    { text: "ship faster with Rival", count: 1, kind: "keyword" },
  ],
  topDomains: [
    { domain: "toolstack.example", links: 1, authority: 72, kind: "editorial" },
    { domain: "techroundup.example", links: 1, authority: 58, kind: "editorial" },
  ],
  insights: [
    {
      id: "demo-insight-3",
      tone: "neutral",
      title: "Fewer links, but a cleaner follow share",
      detail: "Rival has fewer tracked links than you, but a higher share pass authority.",
    },
  ],
};

export const demoCompetitorBacklinks: Record<string, CompetitorBacklink[]> = {
  "demo-comp-1": [
    {
      _id: "demo-cbl-1",
      competitorId: "demo-comp-1",
      sourceUrl: "https://toolstack.example/best-deploy-tools",
      sourceDomain: "toolstack.example",
      targetUrl: "https://rival.example/",
      anchorText: "Rival",
      rel: "follow",
      isImage: false,
      origin: "index",
      status: "live",
      authority: 72,
      lastSeenAt: iso(3 * DAY),
    },
    {
      _id: "demo-cbl-2",
      competitorId: "demo-comp-1",
      sourceUrl: "https://techroundup.example/2026/deploy-tools",
      sourceDomain: "techroundup.example",
      targetUrl: "https://rival.example/pricing",
      anchorText: "ship faster with Rival",
      rel: "follow",
      isImage: false,
      origin: "index",
      status: "live",
      authority: 58,
      lastSeenAt: iso(9 * DAY),
    },
  ],
};

export const demoBacklinkOverview: BacklinkOverview = {
  indexAvailable: true,
  summary: {
    total: 7,
    live: 5,
    referringDomains: 6,
    followShare: 50,
    lost: 1,
    lostRecently: 1,
    newRecently: 2,
    awaiting: 1,
    referralVisits: 2_341,
    opportunities: 1,
  },
  profiles: {
    mine: mineProfile,
    competitors: [
      {
        competitorId: "demo-comp-1",
        label: "Rival",
        domain: "rival.example",
        profile: rivalProfile,
      },
    ],
  },
  gap: {
    opportunities: [
      {
        domain: "techroundup.example",
        kind: "editorial",
        authority: 58,
        competitors: [{ competitorId: "demo-comp-1", label: "Rival" }],
        sampleUrl: "https://techroundup.example/2026/deploy-tools",
        sampleAnchor: "ship faster with Rival",
      },
    ],
    shared: [
      {
        domain: "toolstack.example",
        kind: "editorial",
        authority: 72,
        competitors: [{ competitorId: "demo-comp-1", label: "Rival" }],
        sampleUrl: "https://toolstack.example/best-deploy-tools",
        sampleAnchor: "Acme's pricing page",
      },
    ],
    uniqueToYou: 5,
  },
};
