import {
  Activity, Briefcase, Gauge, Globe, Handshake, Landmark, Magnet, Megaphone, MousePointerClick, Newspaper,
  PenLine, Presentation, Rocket, Route, Search, SearchCheck, ShoppingBag, Smartphone, Sprout, Store,
} from "lucide-react";
import type { Placed, Span, WidgetId } from "@/features/analytics/widgetCatalog";
import type { DashboardTemplate } from "@/features/dashboards/templates";

function grid(...items: [WidgetId, Span][]): Placed[] {
  return items.map(([id, span]) => ({ id, span }));
}

export const TEMPLATE_LIBRARY: DashboardTemplate[] = [
  {
    id: "executive",
    name: "Executive summary",
    tagline: "The numbers leadership asks about",
    description: "Growth, search reach, targets and engagement on one calm screen — no breakdowns to wade through.",
    icon: Presentation,
    accent: "violet",
    category: "Business",
    range: "30d",
    layout: grid(
      ["visitors", 1], ["pageviews", 1], ["searchClicks", 1], ["bounce", 1],
      ["traffic", 4],
      ["targets", 2], ["clicks", 2],
      ["channels", 2], ["seoScore", 2],
    ),
  },
  {
    id: "ecommerce",
    name: "E-commerce",
    tagline: "Traffic, campaigns and what converts",
    description: "Sessions, bounce and clicks next to the channels and campaigns that drive them.",
    icon: ShoppingBag,
    accent: "amber",
    category: "Business",
    range: "7d",
    layout: grid(
      ["visitors", 1], ["sessions", 1], ["bounce", 1], ["avgSession", 1],
      ["traffic", 4],
      ["clicks", 2], ["channels", 1], ["utmCampaigns", 1],
      ["landingPages", 2], ["utmSources", 1], ["devices", 1],
      ["worldMap", 2], ["topPages", 1], ["topReferrers", 1],
    ),
  },
  {
    id: "board",
    name: "Monthly board report",
    tagline: "Growth, reach and outcomes for the month",
    description: "Audience growth, Google reach and goal progress, laid out for a monthly review or investor update.",
    icon: Landmark,
    accent: "blue",
    category: "Business",
    range: "30d",
    layout: grid(
      ["visitors", 1], ["sessions", 1], ["searchImpressions", 1], ["avgSession", 1],
      ["traffic", 3], ["searchPosition", 1],
      ["targets", 2], ["landingPages", 2],
      ["channels", 1], ["topCountries", 1], ["searchTrend", 2],
    ),
  },
  {
    id: "agency",
    name: "Agency client",
    tagline: "A clean monthly story for a client",
    description: "Headline numbers, Google visibility, SEO health and where the audience comes from, ready to screen-share.",
    icon: Briefcase,
    accent: "pink",
    category: "Business",
    range: "30d",
    layout: grid(
      ["visitors", 1], ["pageviews", 1], ["searchClicks", 1], ["bounce", 1],
      ["traffic", 4],
      ["searchQueries", 2], ["seoScore", 2],
      ["topReferrers", 1], ["channels", 1], ["topCountries", 1], ["devices", 1],
      ["worldMap", 2], ["topPages", 2],
    ),
  },
  {
    id: "local",
    name: "Local business",
    tagline: "Who's nearby, and what they search for",
    description: "Phone-first visitors, calls and directions clicks, the searches that find you, and where your audience lives.",
    icon: Store,
    accent: "teal",
    category: "Business",
    range: "7d",
    layout: grid(
      ["visitors", 1], ["live", 1], ["searchClicks", 1], ["bounce", 1],
      ["traffic", 3], ["livePages", 1],
      ["clicks", 2], ["worldMap", 2],
      ["searchQueries", 2], ["devices", 1], ["topReferrers", 1],
    ),
  },
  {
    id: "global",
    name: "International audience",
    tagline: "Where your audience lives and what it speaks",
    description: "Countries, languages and devices around the world, with the pages each market reads most.",
    icon: Globe,
    accent: "cyan",
    category: "Business",
    range: "30d",
    layout: grid(
      ["visitors", 1], ["sessions", 1], ["avgSession", 1], ["bounce", 1],
      ["worldMap", 4],
      ["topCountries", 1], ["languages", 1], ["devices", 1], ["channels", 1],
      ["traffic", 2], ["topPages", 2],
    ),
  },
  {
    id: "campaigns",
    name: "Campaign performance",
    tagline: "Which campaigns earn their budget",
    description: "UTM sources and campaigns side by side with the landing pages and goals they feed.",
    icon: Megaphone,
    accent: "orange",
    category: "Marketing",
    range: "7d",
    layout: grid(
      ["sessions", 1], ["visitors", 1], ["bounce", 1], ["avgSession", 1],
      ["utmCampaigns", 2], ["utmSources", 2],
      ["traffic", 4],
      ["landingPages", 2], ["clicks", 2],
      ["channels", 2], ["topReferrers", 2],
    ),
  },
  {
    id: "organic",
    name: "Organic growth",
    tagline: "Search rankings next to the visits they earn",
    description: "Google clicks and positions beside on-site engagement, so you can see which rankings actually bring people in.",
    icon: Sprout,
    accent: "emerald",
    category: "Marketing",
    range: "30d",
    layout: grid(
      ["searchClicks", 1], ["visitors", 1], ["searchPosition", 1], ["bounce", 1],
      ["searchTrend", 4],
      ["searchQueries", 2], ["landingPages", 2],
      ["channels", 1], ["topReferrers", 1], ["searchOpportunities", 2],
    ),
  },
  {
    id: "acquisition",
    name: "Acquisition channels",
    tagline: "Every traffic source, ranked by what it brings",
    description: "Channels, referrers and UTM sources with the entry pages and goals each one feeds.",
    icon: Route,
    accent: "blue",
    category: "Marketing",
    range: "7d",
    layout: grid(
      ["sessions", 1], ["visitors", 1], ["bounce", 1], ["pagesPerSession", 1],
      ["channels", 2], ["utmSources", 2],
      ["traffic", 4],
      ["topReferrers", 1], ["utmCampaigns", 1], ["entryPages", 2],
      ["clicks", 2], ["landingPages", 2],
    ),
  },
  {
    id: "leadgen",
    name: "Lead generation",
    tagline: "From first click to filled-in form",
    description: "Targets for leads, the pages that convert, and the CTAs people actually press.",
    icon: Magnet,
    accent: "emerald",
    category: "Marketing",
    range: "30d",
    layout: grid(
      ["visitors", 1], ["sessions", 1], ["pagesPerSession", 1], ["bounce", 1],
      ["targets", 2], ["scrollDepth", 2],
      ["landingPages", 2], ["clicks", 2],
      ["channels", 1], ["utmSources", 1], ["entryPages", 2],
    ),
  },
  {
    id: "search",
    name: "Search visibility",
    tagline: "Clicks, rankings and queries straight from Google",
    description: "Everything Google Search reports about your site: reach, rankings, the queries that find you and the quick wins to chase next.",
    icon: Search,
    accent: "emerald",
    category: "Search",
    range: "30d",
    layout: grid(
      ["searchClicks", 1], ["searchImpressions", 1], ["searchCtr", 1], ["searchPosition", 1],
      ["searchTrend", 4],
      ["searchRankings", 2], ["searchOpportunities", 2],
      ["searchQueries", 2], ["searchPages", 2],
    ),
  },
  {
    id: "seo",
    name: "SEO health",
    tagline: "Audit score, rankings and organic landings",
    description: "Your latest audit next to where you rank in Google and the pages search sends people to.",
    icon: SearchCheck,
    accent: "violet",
    category: "Search",
    range: "30d",
    layout: grid(
      ["seoScore", 2], ["searchRankings", 2],
      ["searchClicks", 1], ["searchPosition", 1], ["searchCtr", 1], ["visitors", 1],
      ["searchPages", 2], ["landingPages", 2],
      ["searchOpportunities", 2], ["topReferrers", 1], ["topCountries", 1],
    ),
  },
  {
    id: "seoclient",
    name: "SEO client report",
    tagline: "A monthly search story to share with a client",
    description: "Google reach, rankings and the queries that grew, with the audit score that shows the work behind them.",
    icon: Handshake,
    accent: "pink",
    category: "Search",
    range: "30d",
    layout: grid(
      ["searchClicks", 1], ["searchImpressions", 1], ["searchPosition", 1], ["visitors", 1],
      ["searchTrend", 4],
      ["searchQueries", 2], ["searchPages", 2],
      ["seoScore", 2], ["searchRankings", 2],
    ),
  },
  {
    id: "content",
    name: "Content & blog",
    tagline: "What people read, how far, and how they found it",
    description: "Top articles, reading depth and time on page, plus the searches and sites that send readers.",
    icon: Newspaper,
    accent: "blue",
    category: "Content",
    range: "30d",
    layout: grid(
      ["pageviews", 1], ["visitors", 1], ["avgSession", 1], ["bounce", 1],
      ["traffic", 4],
      ["topPages", 2], ["scrollDepth", 2],
      ["searchQueries", 2], ["topReferrers", 1], ["entryPages", 1],
      ["searchPages", 2], ["languages", 1], ["topCountries", 1],
    ),
  },
  {
    id: "editorial",
    name: "Editorial performance",
    tagline: "Which stories land, and how they're found",
    description: "Reading depth and engagement per story, next to the Google queries that bring readers in.",
    icon: PenLine,
    accent: "amber",
    category: "Content",
    range: "7d",
    layout: grid(
      ["pageviews", 1], ["avgSession", 1], ["pagesPerSession", 1], ["searchClicks", 1],
      ["topPages", 2], ["scrollDepth", 2],
      ["entryPages", 1], ["exitPages", 1], ["searchQueries", 2],
      ["traffic", 4],
    ),
  },
  {
    id: "saas",
    name: "SaaS metrics",
    tagline: "Activation, engagement and reliability",
    description: "How deep visits go, which goals convert, what breaks, and when people show up.",
    icon: Gauge,
    accent: "cyan",
    category: "Product",
    range: "30d",
    layout: grid(
      ["visitors", 1], ["sessions", 1], ["avgSession", 1], ["pagesPerSession", 1],
      ["traffic", 3], ["live", 1],
      ["targets", 2], ["clicks", 2],
      ["entryPages", 1], ["exitPages", 1], ["channels", 1], ["errors", 1],
      ["heatmap", 4],
    ),
  },
  {
    id: "launch",
    name: "Product launch",
    tagline: "Follow a launch hour by hour",
    description: "Who's arriving right now, where from, and what's breaking — tuned to the last 24 hours.",
    icon: Rocket,
    accent: "orange",
    category: "Product",
    range: "24h",
    layout: grid(
      ["live", 1], ["visitors", 1], ["sessions", 1], ["pageviews", 1],
      ["traffic", 3], ["livePages", 1],
      ["topReferrers", 1], ["utmSources", 1], ["channels", 2],
      ["worldMap", 2], ["errors", 2],
    ),
  },
  {
    id: "live",
    name: "Live operations",
    tagline: "A wall screen for launch day",
    description: "Who's on the site right now, where they are, what they're viewing and what's breaking.",
    icon: Activity,
    accent: "teal",
    category: "Product",
    range: "24h",
    layout: grid(
      ["live", 1], ["visitors", 1], ["pageviews", 1], ["sessions", 1],
      ["worldMap", 2], ["livePages", 2],
      ["traffic", 4],
      ["errors", 2], ["outbound", 2],
    ),
  },
  {
    id: "ux",
    name: "UX & engagement",
    tagline: "Where people scroll, click and leave",
    description: "Scroll depth, click maps, exit pages and device mix to find friction fast.",
    icon: MousePointerClick,
    accent: "blue",
    category: "Product",
    range: "7d",
    layout: grid(
      ["avgSession", 1], ["pagesPerSession", 1], ["bounce", 1], ["sessions", 1],
      ["scrollDepth", 2], ["clicks", 2],
      ["exitPages", 1], ["screenSizes", 1], ["devices", 1], ["browsers", 1],
      ["heatmap", 4],
      ["errors", 2],
    ),
  },
  {
    id: "mobile",
    name: "Mobile experience",
    tagline: "How the site holds up on phones and tablets",
    description: "Device, screen and OS mix next to bounce, scroll depth and the errors that only show up on small screens.",
    icon: Smartphone,
    accent: "pink",
    category: "Product",
    range: "7d",
    layout: grid(
      ["bounce", 1], ["avgSession", 1], ["pagesPerSession", 1], ["sessions", 1],
      ["devices", 1], ["screenSizes", 1], ["operatingSystems", 1], ["browsers", 1],
      ["scrollDepth", 2], ["exitPages", 2],
      ["errors", 2], ["clicks", 2],
    ),
  },
];
